name: App Distribution Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: version(x.xx.x format)
        type: string
        default: "99.0.0"
      build_flavor:
        description: "Select Build Flavor"
        required: true
        type: choice
        default: staging
        options:
          - production
          - staging
      trigger_android_apk_dev_build:
        description: "Android APK Dev Build"
        type: boolean
        default: true
      trigger_android_playstore_dev_build:
        description: "Android Play Store Dev Build"
        type: boolean
        default: false
      trigger_ios_app_dev_build:
        description: "iOS App Dev Build"
        type: boolean
        default: true
      trigger_android_playstore_release_build:
        if: ${{ build_flavor == 'production' }}
        description: "Android Play Store Release Build"
        type: boolean
        default: false
      trigger_ios_app_release_build:
        if: ${{ build_flavor == 'production' }}
        description: "iOS App Release Build"
        type: boolean
        default: true
      trigger_ios_app_firebase_distribution_build:
        if: ${{ build_flavor == 'production' }}
        description: "iOS App Release Build"
        type: boolean
        default: true

jobs:
  android-apk-build:
    if: ${{ inputs.trigger_android_apk_dev_build }}
    uses: ./.github/workflows/trigger-android-build.yml
    with:
      version: ${{ inputs.version }}
      build_flavor: ${{ inputs.build_flavor }}
      build_distribution: apk
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  android-playstore-build:
    if: ${{ inputs.trigger_android_playstore_dev_build }}
    uses: ./.github/workflows/trigger-android-build.yml
    with:
      version: ${{ inputs.version }}
      build_flavor: ${{ inputs.build_flavor }}
      build_distribution: playstore
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  ios-build:
    if: ${{ inputs.trigger_ios_app_dev_build }}
    uses: ./.github/workflows/trigger-ios-build.yml
    with:
      version: ${{ inputs.version }}
      build_flavor: ${{ inputs.build_flavor }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
