name: Android Build

on:
  workflow_call:
    inputs:
      build_flavor:
        type: string
        default: staging
      build_distribution:
        type: string
        default: apk
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_TOKEN:
        required: true

  workflow_dispatch:
    inputs:
      build_flavor:
        description: "Build flavor"
        required: false
        default: staging
        type: choice
        options:
          - staging
          - production
      build_distribution:
        description: "Distribution type"
        required: false
        default: apk
        type: choice
        options:
          - apk
          - playstore

env:
  APP_ENV: ${{ inputs.build_flavor }}
  DISTRIBUTION: ${{ inputs.build_distribution }}

jobs:
  build:
    name: ${{ inputs.build_flavor }}-${{ inputs.build_distribution }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android App
        id: build
        env:
          EAS_LOCAL_BUILD: true
          EXPO_TOKEN: 5oPgsw8-tg2cP3JeoR9IRrhoCI-EQt2-qoAJrFJk
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "📦 Building Android for ${{ env.APP_ENV }}-${{env.DISTRIBUTION}}"
          yarn build:${{env.APP_ENV}}:${{env.DISTRIBUTION}}

          FILE_PATH=$(find . -type f \( -name "*.apk" -o -name "*.aab" \) | head -n 1)
          echo "FILE_PATH=${FILE_PATH}" >> $GITHUB_OUTPUT

      - name: Send Build to Slack
        uses: ./.github/actions/slack-alert
        with:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ vars.ANDROID_BUILDS_CHANNEL }}
          WORKFLOW_NAME: "${{inputs.build_distribution}} Build"
          WORKFLOW_STATUS: ${{ job.status }}
          BUILD_FLAVOR: ${{inputs.build_flavor}}
          BRANCH_NAME: ${{ github.head_ref }}
          FILE_PATH: ${{ steps.build.outputs.FILE_PATH }}