name: iOS Build

on:
  workflow_call:
    inputs:
      build_flavor:
        type: string
        default: staging
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_TOKEN:
        required: true

  workflow_dispatch:
    inputs:
      build_flavor:
        description: "Build flavor"
        required: false
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  ios-build:
    name: ${{ inputs.build_flavor }}
    runs-on: keystone-runner-ios
    steps:
      - name: Clean working directory
        shell: bash
        run: |
          echo "🧹 Cleaning up previous run"
          sudo chown -R $USER /Users/$USER/keystone-actions-runner/_keystone_work/keystone/
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Ruby
        run: |
          ruby -v
          rvm list
          rvm use ruby-3.2.2 --default

      - name: Run iOS build
        id: build
        env:
          EAS_LOCAL_BUILD: true
          EXPO_TOKEN: 5oPgsw8-tg2cP3JeoR9IRrhoCI-EQt2-qoAJrFJk
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          APP_ENV: ${{ inputs.build_flavor }}
          DISTRIBUTION: ios
        run: |
          echo "📦 Building iOS for ${{ env.APP_ENV }}-${{env.DISTRIBUTION}}"
          yarn build:${{env.APP_ENV}}:${{env.DISTRIBUTION}}

          FILE_PATH=$(find . -type f \( -name "*.app" -o -name "*.ipa" -o -name "*.tar.gz" \) | head -n 1)
          echo "FILE_PATH=${FILE_PATH}" >> $GITHUB_OUTPUT

      - name: Send Build to Slack
        uses: ./.github/actions/slack-alert
        with:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ vars.IOS_BUILDS_CHANNEL }}
          WORKFLOW_NAME: "iOS Build"
          WORKFLOW_STATUS: ${{ job.status }}
          BUILD_FLAVOR: ${{inputs.build_flavor}}
          BRANCH_NAME: ${{ github.head_ref }}
          FILE_PATH: ${{ steps.build.outputs.FILE_PATH }}