name: Trigger Build

on:
  workflow_dispatch:
    inputs:
      build_flavor:
        description: "Select Build Flavor"
        required: true
        type: choice
        default: staging
        options:
          - production
          - staging
      trigger_android_apk_distribution:
        description: "Android APK Distribution"
        type: boolean
        default: true
      trigger_android_playstore_distribution:
        description: "Android Play Store Distribution"
        type: boolean
        default: false
      trigger_ios_app_distribution:
        description: "iOS App Distribution"
        type: boolean
        default: true

jobs:
  jobs:
  android-build:
    name: Android Build - ${{ matrix.build_distribution }}
    strategy:
      matrix:
        build_distribution: [apk, playstore]
    if: |
      (matrix.build_distribution == 'apk' && inputs.trigger_android_apk_distribution == true) ||
      (matrix.build_distribution == 'playstore' && inputs.trigger_android_playstore_distribution == true)
    uses: ./.github/workflows/eas-android-build.yml
    with:
      build_flavor: ${{ inputs.build_flavor }}
      build_distribution: ${{ matrix.build_distribution }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}


  ios-build:
    if: ${{ true }}
    uses: ./.github/workflows/eas-ios-build.yml
    with:
      build_flavor: staging
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}