name: Trigger Build

on:
  workflow_dispatch:
    inputs:
      build_flavor:
        description: "Select Build Flavor"
        required: true
        type: choice
        default: staging
        options:
          - production
          - staging

      trigger_android_apk_distribution:
        description: "Run Android APK build"
        type: boolean
        default: true

      trigger_android_playstore_distribution:
        description: "Run Android Play Store build"
        type: boolean
        default: false

      trigger_ios_app_distribution:
        description: "Run iOS build"
        type: boolean
        default: true

jobs:
  # ──────────────────────────────────────────────────────────────
  android-apk:
    name: Android APK Build
    if: ${{ github.event.inputs.trigger_android_apk_distribution == 'true' }}
    uses: ./.github/workflows/eas-android-build.yml
    with:
      build_flavor:      ${{ github.event.inputs.build_flavor }}
      build_distribution: apk
    secrets:
      NPM_TOKEN:   ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

  # ──────────────────────────────────────────────────────────────
  android-playstore:
    name: Android Play Store Build
    if: ${{ github.event.inputs.trigger_android_playstore_distribution == 'true' }}
    uses: ./.github/workflows/eas-android-build.yml
    with:
      build_flavor:      ${{ github.event.inputs.build_flavor }}
      build_distribution: playstore
    secrets:
      NPM_TOKEN:   ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

  # ──────────────────────────────────────────────────────────────
  ios-build:
    name: iOS Build
    if: ${{ github.event.inputs.trigger_ios_app_distribution == 'true' }}
    uses: ./.github/workflows/eas-ios-build.yml
    with:
      build_flavor: ${{ github.event.inputs.build_flavor }}
    secrets:
      NPM_TOKEN:   ${{ secrets.NPM_TOKEN }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
